# Generated by Django 3.0.1 on 2020-02-11 00:48

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200101_0122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', users.managers.MyUserManager()),
            ],
        ),
    ]
