# Generated by Django 3.0.1 on 2019-12-23 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('USA', 'United States'), ('GBR', 'United Kingdom'), ('CAN', 'Canada'), ('AUS', 'Australia')], max_length=3)),
                ('state', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=70)),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=511)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_timestamp', models.DateTimeField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('body', models.CharField(max_length=2047)),
                ('slug', models.SlugField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited_timestamp', models.DateTimeField(null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
