# Generated by Django 3.0.1 on 2019-12-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_auto_20191224_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='colleges.Thread'),
        ),
    ]
