# Generated by Django 3.0.1 on 2020-01-01 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0004_auto_20191230_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='AnonymousName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.Thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
