# Generated by Django 3.0.1 on 2019-12-26 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colleges', '0006_commentvote_threadvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='is_upvote',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentvote',
            name='voter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentvote_votes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='is_upvote',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadvote_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
