# Generated by Django 3.0.1 on 2019-12-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_auto_20191225_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to='colleges.Comment'),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_votes', to='colleges.Thread'),
        ),
    ]
