# Generated by Django 3.0.1 on 2020-01-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_auto_20191231_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeemail',
            name='domain',
            field=models.CharField(max_length=31),
        ),
    ]
